# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20190724_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_path',
            field=models.ImageField(default='pictures/juliet.jpg', upload_to='pictures/'),
        ),
    ]
