# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20190724_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_path',
            field=models.ImageField(default='images/juliet.jpg', upload_to='images/'),
        ),
    ]
